# Cluster Analysis

Differences between groups were tested using a Chi-squared test for categorical variables and a one-way ANOVA for continuous variables.

In [1]:
%reload_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import seaborn as sn

from IPython.display import display

from preproc import get_hfpef_200, convert2np, get_hfpef_200

from scipy.stats import f_oneway, chi2_contingency

from sklearn.metrics.cluster import contingency_matrix

np.set_printoptions(precision=3, suppress=True)
pd.options.display.float_format = "{:,.3f}".format

In [2]:
data_df = get_hfpef_200()

In [4]:
data_df.describe()

,Age,Sex,Cr,GFR,CKD stage,smoke,BMI,BSA,DM,Insulin,...,E/A,Mitral E/e',TR Vmax,RWT,LV mass index,LVH,LAVI,LACI,LA diameter,LVEF
count,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,...,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000
mean,72.045,1.680,1.711,52.293,2.810,0.105,26.739,1.633,0.560,0.215,...,0.742,17.301,1.890,0.648,115.641,2.640,31.987,3.212,3.670,61.435
std,11.405,0.468,1.535,25.189,1.044,0.307,6.637,0.228,0.498,0.412,...,0.607,8.602,1.444,0.388,52.779,1.897,26.285,3.989,1.446,8.421
min,31.000,1.000,0.550,2.000,1.000,0.000,15.400,1.120,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,65.000,1.000,0.887,34.750,2.000,0.000,22.200,1.485,0.000,0.000,...,0.500,11.600,0.000,0.400,86.725,1.000,0.000,0.000,3.500,56.000
50%,74.000,2.000,1.140,54.000,3.000,0.000,26.300,1.600,1.000,0.000,...,0.700,16.300,2.460,0.555,113.150,2.500,32.600,2.480,4.000,61.000
75%,80.000,2.000,1.792,70.250,3.000,0.000,29.925,1.800,1.000,0.000,...,1.000,22.100,3.002,0.865,141.305,4.000,48.425,5.111,4.400,66.000
max,97.000,2.000,10.000,108.000,5.000,1.000,55.900,2.300,1.000,1.000,...,4.100,42.200,4.550,2.300,356.600,7.000,140.800,23.665,6.200,82.900

## Get Cluster

In [5]:
from methods import get_sc_pred, get_p_ci
from utils import get_score, score_columns, plot_clustering_score, plot_contingency_matrix, plot_bic_aic

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

In [6]:
lbl_colname= ['Death', 'CV death', 'Major cardiac events']

## Analysis

In [7]:
X, y, feature_list = convert2np(data_df, lbl_colname)
y_pred = get_sc_pred(3, X)

feat_df, cluster_df = get_p_ci(data_df, y_pred)
display(feat_df)
display(cluster_df)
cluster_df.to_excel("HFpEF_allfeat_spectral_3clus_200samples.xlsx")

                      p-value  is_category
Age                     0.693        False
Sex                     0.586         True
Cr                      0.000        False
GFR                     0.000        False
CKD stage               0.001         True
smoke                   0.512         True
BMI                     0.000        False
BSA                     0.076        False
DM                      0.296         True
Insulin                 0.436         True
AF                      0.565         True
SBP                     0.092        False
DBP                     0.476        False
MAP                     0.798        False
PP                      0.019        False
1/2SBP                  0.092        False
wide PP                 0.053         True
HR                      0.965        False
ACE-i                   0.922         True
ARB                     0.001         True
ARNI                    0.001         True
betablocker             0.103         True
Aspirin                 0.591         True
SGLT2i                  0.080         True
MRA                     0.831         True
MI                      0.065         True
stroke                  0.001         True
COPD                    0.120         True
NYHA                    0.236         True
edema                   0.456         True
Death                   0.371         True
CV death                0.080         True
Major cardiac events    0.000         True
NTProBNP                0.000        False
medial a'               0.590        False
medial E'               0.566        False
lateral E'              0.806        False
average e/E'            0.244        False
lateral e/E'            0.377        False
E/A                     0.281        False
Mitral E/e'             0.016        False
TR Vmax                 0.010        False
RWT                     0.507        False
LV mass index           0.004        False
LVH                     0.347         True
LAVI                    0.381        False
LACI                    0.202        False
LA diameter             0.474        False
LVEF                    0.482        False

,0_mu,0_ci_l,0_ci_h,1_mu,1_ci_l,1_ci_h,2_mu,2_ci_l,2_ci_h,p-value
n,75.000,0.000,0.000,52.000,0.000,0.000,73.000,0.000,0.000,0.000
Sex_1,21.000,28.000,0.000,19.000,36.538,0.000,24.000,32.877,0.000,0.586
Sex_2,54.000,72.000,0.000,33.000,63.462,0.000,49.000,67.123,0.000,0.586
CKD stage_1,4.000,5.333,0.000,1.000,1.923,0.000,11.000,15.068,0.000,0.001
CKD stage_2,27.000,36.000,0.000,14.000,26.923,0.000,25.000,34.247,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...
LV mass index,110.663,97.052,124.275,136.137,121.508,150.767,106.155,97.244,115.066,0.004
LAVI,32.889,26.551,39.228,35.183,27.873,42.493,28.784,23.295,34.272,0.381
LACI,2.775,1.981,3.570,4.037,2.701,5.372,3.072,2.229,3.915,0.202
LA diameter,3.722,3.418,4.025,3.817,3.440,4.195,3.512,3.148,3.877,0.474
LVEF,60.581,58.421,62.742,62.381,60.271,64.490,61.637,59.887,63.387,0.482

In [8]:
X, y, feature_list = convert2np(data_df, lbl_colname, selected_feat=True)
y_pred = get_sc_pred(2, X)

feat_df, cluster_df = get_p_ci(data_df, y_pred)
display(feat_df)
display(cluster_df)
cluster_df.to_excel("HFpEF_selfeat_spectral_2clus_200samples.xlsx")

                      p-value  is_category
Age                     0.086        False
Sex                     0.265         True
Cr                      0.838        False
GFR                     0.409        False
CKD stage               0.464         True
smoke                   0.269         True
BMI                     0.003        False
BSA                     0.311        False
DM                      0.466         True
Insulin                 0.658         True
AF                      0.441         True
SBP                     0.223        False
DBP                     0.083        False
MAP                     0.525        False
PP                      0.018        False
1/2SBP                  0.223        False
wide PP                 0.030         True
HR                      0.339        False
ACE-i                   0.464         True
ARB                     0.034         True
ARNI                    0.025         True
betablocker             0.584         True
Aspirin                 0.997         True
SGLT2i                  0.068         True
MRA                     0.632         True
MI                      0.181         True
stroke                  0.001         True
COPD                    0.049         True
NYHA                    0.437         True
edema                   0.084         True
Death                   0.013         True
CV death                0.129         True
Major cardiac events    0.000         True
NTProBNP                0.000        False
medial a'               0.727        False
medial E'               0.747        False
lateral E'              0.423        False
average e/E'            0.878        False
lateral e/E'            0.338        False
E/A                     0.502        False
Mitral E/e'             0.678        False
TR Vmax                 0.000        False
RWT                     0.415        False
LV mass index           0.132        False
LVH                     0.666         True
LAVI                    0.865        False
LACI                    0.281        False
LA diameter             0.662        False
LVEF                    0.529        False

                 0_mu  0_ci_l  0_ci_h    1_mu  1_ci_l  1_ci_h  p-value
n             101.000   0.000   0.000  99.000   0.000   0.000    0.000
Sex_1          36.000  35.644   0.000  28.000  28.283   0.000    0.265
Sex_2          65.000  64.356   0.000  71.000  71.717   0.000    0.265
CKD stage_1     8.000   7.921   0.000   8.000   8.081   0.000    0.464
CKD stage_2    28.000  27.723   0.000  38.000  38.384   0.000    0.464
...               ...     ...     ...     ...     ...     ...      ...
LV mass index 121.205 111.348 131.063 109.964  99.201 120.727    0.132
LAVI           32.302  27.013  37.591  31.666  26.635  36.696    0.865
LACI            3.513   2.619   4.407   2.904   2.260   3.548    0.281
LA diameter     3.715   3.414   4.015   3.625   3.359   3.891    0.662
LVEF           61.807  60.389  63.224  61.055  59.188  62.921    0.529

[84 rows x 7 columns]