# Cluster Analysis

Differences between groups were tested using a Chi-squared test for categorical variables and a one-way ANOVA for continuous variables.

In [1]:
%reload_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import seaborn as sn

from IPython.display import display

from preproc import get_hfpef_200, convert2np, get_hfpef_200

from scipy.stats import f_oneway, chi2_contingency

from sklearn.metrics.cluster import contingency_matrix

np.set_printoptions(precision=3, suppress=True)
pd.options.display.float_format = "{:,.3f}".format

In [2]:
data_df = get_hfpef_200()

## Get Cluster

In [4]:
from methods import get_sc_pred, get_p_ci
from utils import get_score, score_columns, plot_clustering_score, plot_contingency_matrix, plot_bic_aic

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

In [5]:
lbl_colname= ['Death', 'CV death', 'Major cardiac events']

## Analysis

In [6]:
X, y, feature_list = convert2np(data_df, lbl_colname)
y_pred = get_sc_pred(3, X)

feat_df, cluster_df = get_p_ci(data_df, y_pred)
display(feat_df)
display(cluster_df)
# cluster_df.to_excel("HFpEF_allfeat_spectral_3clus_200samples.xlsx")

                      p-value  is_category
Age                     0.661        False
Sex                     0.730         True
Cr                      0.000        False
GFR                     0.000        False
CKD stage               0.001         True
smoke                   0.276         True
BMI                     0.000        False
BSA                     0.077        False
DM                      0.618         True
Insulin                 0.595         True
AF                      0.462         True
SBP                     0.080        False
DBP                     0.711        False
MAP                     0.790        False
PP                      0.029        False
1/2SBP                  0.080        False
wide PP                 0.088         True
HR                      0.953        False
ACE-i                   0.999         True
ARB                     0.000         True
ARNI                    0.001         True
betablocker             0.228         True
Aspirin                 0.590         True
SGLT2i                  0.074         True
MRA                     0.881         True
MI                      0.106         True
stroke                  0.000         True
COPD                    0.125         True
NYHA                    0.446         True
edema                   0.580         True
Death                   0.125         True
CV death                0.015         True
Major cardiac events    0.000         True
NTProBNP                0.000        False
medial a'               0.722        False
medial E'               0.287        False
lateral E'              0.457        False
average e/E'            0.174        False
lateral e/E'            0.448        False
E/A                     0.329        False
Mitral E/e'             0.025        False
TR Vmax                 0.014        False
RWT                     0.434        False
LV mass index           0.006        False
LVH                     0.358         True
LAVI                    0.977        False
LACI                    0.329        False
LA diameter             0.827        False
LVEF                    0.443        False

,0_mu,0_ci_l,0_ci_h,1_mu,1_ci_l,1_ci_h,2_mu,2_ci_l,2_ci_h,p-value
n,73.000,0.000,0.000,54.000,0.000,0.000,73.000,0.000,0.000,0.000
Sex_1,21.000,28.767,0.000,19.000,35.185,0.000,24.000,32.877,0.000,0.730
Sex_2,52.000,71.233,0.000,35.000,64.815,0.000,49.000,67.123,0.000,0.730
CKD stage_1,4.000,5.479,0.000,1.000,1.852,0.000,11.000,15.068,0.000,0.001
CKD stage_2,27.000,36.986,0.000,15.000,27.778,0.000,24.000,32.877,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...
LV mass index,111.053,97.101,125.005,134.843,120.642,149.045,106.025,97.077,114.972,0.006
LAVI,16.864,3.949,29.778,16.781,1.719,31.843,18.473,8.251,28.694,0.977
LACI,2.851,2.042,3.661,3.887,2.585,5.189,3.072,2.229,3.915,0.329
LA diameter,17.839,13.641,22.037,16.325,11.461,21.190,16.106,11.940,20.272,0.827
LVEF,60.473,58.258,62.687,62.311,60.258,64.364,61.748,60.007,63.488,0.443

In [7]:
X, y, feature_list = convert2np(data_df, lbl_colname, selected_feat=True)
y_pred = get_sc_pred(2, X)

feat_df, cluster_df = get_p_ci(data_df, y_pred)
display(feat_df)
display(cluster_df)
# cluster_df.to_excel("HFpEF_selfeat_spectral_2clus_200samples.xlsx")

C:\Users\HP\miniconda3\lib\site-packages\sklearn\manifold\_spectral_embedding.py:245: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn("Graph is not fully connected, spectral embedding"

                      p-value  is_category
Age                     0.846        False
Sex                     0.338         True
Cr                      0.118        False
GFR                     0.286        False
CKD stage               0.174         True
smoke                   0.267         True
BMI                     0.925        False
BSA                     0.785        False
DM                      0.990         True
Insulin                 0.164         True
AF                      0.097         True
SBP                     0.138        False
DBP                     0.975        False
MAP                     0.439        False
PP                      0.162        False
1/2SBP                  0.138        False
wide PP                 0.382         True
HR                      0.737        False
ACE-i                   0.422         True
ARB                     0.453         True
ARNI                    0.143         True
betablocker             0.144         True
Aspirin                 0.849         True
SGLT2i                  0.340         True
MRA                     0.681         True
MI                      0.111         True
stroke                  0.008         True
COPD                    0.248         True
NYHA                    0.462         True
edema                   0.376         True
Death                   0.028         True
CV death                0.027         True
Major cardiac events    0.000         True
NTProBNP                0.000        False
medial a'               0.224        False
medial E'               0.130        False
lateral E'              0.561        False
average e/E'            0.374        False
lateral e/E'            0.911        False
E/A                     0.033        False
Mitral E/e'             0.503        False
TR Vmax                 0.047        False
RWT                     0.624        False
LV mass index           0.440        False
LVH                     0.224         True
LAVI                    0.000        False
LACI                    0.469        False
LA diameter             0.028        False
LVEF                    0.333        False

                 0_mu  0_ci_l  0_ci_h    1_mu  1_ci_l  1_ci_h  p-value
n              59.000   0.000   0.000 141.000   0.000   0.000    0.000
Sex_1          16.000  27.119   0.000  48.000  34.043   0.000    0.338
Sex_2          43.000  72.881   0.000  93.000  65.957   0.000    0.338
CKD stage_1     3.000   5.085   0.000  13.000   9.220   0.000    0.174
CKD stage_2    21.000  35.593   0.000  45.000  31.915   0.000    0.174
...               ...     ...     ...     ...     ...     ...      ...
LV mass index 111.169  95.385 126.954 117.512 109.490 125.534    0.440
LAVI           41.808  35.447  48.170   7.227  -2.178  16.632    0.000
LACI            3.528   2.607   4.449   3.079   2.395   3.763    0.469
LA diameter    21.149  16.325  25.974  14.977  12.074  17.880    0.028
LVEF           60.541  57.908  63.174  61.809  60.571  63.046    0.333

[84 rows x 7 columns]